"""Verification for app.semver_npm against the real node-semver.

The oracle fixture (``fixtures/semver_oracle.json``) was generated by running
every (version, range) pair through the actual ``semver`` npm package
(``scratchpad/gen_oracle.cjs``, semver 7.8.5 on node v26) - 7622 satisfies
rows spanning carets, tildes, x-ranges, hyphen partials, ``||`` alternatives,
prerelease gates and invalid inputs, plus 32 maxSatisfying cases. The tests
replay it offline and demand agreement on every row.

Runnable two ways:
  * pytest backend/tests/test_semver_npm.py
  * backend/.venv/bin/python backend/tests/test_semver_npm.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.semver_npm import max_satisfying, satisfies  # noqa: E402

_FIXTURE = Path(__file__).resolve().parent / "fixtures" / "semver_oracle.json"


def _load_oracle() -> dict:
    with _FIXTURE.open() as handle:
        return json.load(handle)


# --- oracle replay ----------------------------------------------------------


def test_oracle_satisfies():
    """Agree with node-semver on every generated (version, range) row."""
    oracle = _load_oracle()
    rows = oracle["satisfies"]
    mismatches = [
        (version, range_, expected, satisfies(version, range_))
        for version, range_, expected in rows
        if satisfies(version, range_) is not expected
    ]
    detail = "\n".join(
        f"  satisfies({v!r}, {r!r}) -> {got}, node-semver says {want}"
        for v, r, want, got in mismatches[:25]
    )
    assert not mismatches, (
        f"{len(mismatches)}/{len(rows)} rows disagree with "
        f"node-semver {oracle['semver_version']}:\n{detail}"
    )


def test_oracle_max_satisfying():
    """Agree with node-semver's maxSatisfying, including the returned spelling."""
    oracle = _load_oracle()
    rows = oracle["max_satisfying"]
    mismatches = [
        (versions, range_, expected, max_satisfying(versions, range_))
        for versions, range_, expected in rows
        if max_satisfying(versions, range_) != expected
    ]
    detail = "\n".join(
        f"  max_satisfying({v!r}, {r!r}) -> {got!r}, node-semver says {want!r}"
        for v, r, want, got in mismatches
    )
    assert not mismatches, (
        f"{len(mismatches)}/{len(rows)} maxSatisfying cases disagree:\n{detail}"
    )


# --- targeted regression tests (independent of the fixture) -----------------


def test_prerelease_ordering_semver_11():
    """1.0.0-alpha < 1.0.0-alpha.1 < ... < 1.0.0-rc.1 < 1.0.0, per SemVer §11."""
    chain = [
        "1.0.0-alpha", "1.0.0-alpha.1", "1.0.0-alpha.beta", "1.0.0-beta",
        "1.0.0-beta.2", "1.0.0-beta.11", "1.0.0-rc.1", "1.0.0",
    ]
    for lower, higher in zip(chain, chain[1:]):
        # '>lower' mentions a prerelease on the same [1,0,0] tuple, so the
        # gate admits the prerelease candidates.
        assert satisfies(higher, f">{lower}"), f"{higher} should be > {lower}"
        assert not satisfies(lower, f">={higher}"), f"{lower} should be < {higher}"


def test_build_metadata_ignored():
    assert satisfies("1.2.3+build.5", "1.2.3")
    assert satisfies("1.2.3", "=1.2.3+other")
    assert satisfies("1.2.3+a.b", ">=1.2.3 <1.2.4")
    assert max_satisfying(["1.2.3+a", "1.2.3+b"], "1.2.3") == "1.2.3+a"  # tie: first wins


def test_caret_leftmost_nonzero():
    assert satisfies("1.9.9", "^1.2.3") and not satisfies("2.0.0", "^1.2.3")
    assert satisfies("0.2.9", "^0.2.3") and not satisfies("0.3.0", "^0.2.3")
    assert satisfies("0.0.3", "^0.0.3") and not satisfies("0.0.4", "^0.0.3")
    assert not satisfies("2.0.0-rc.1", "^1.2.3")  # upper bound is <2.0.0-0


def test_tilde_forms():
    assert satisfies("1.2.99", "~1.2.3") and not satisfies("1.3.0", "~1.2.3")
    assert satisfies("1.2.0", "~1.2") and not satisfies("1.3.0", "~1.2")
    assert satisfies("1.9.9", "~1") and not satisfies("2.0.0", "~1")
    assert satisfies("1.2.3-alpha.7", "~1.2.3-alpha.3")  # same-tuple gate
    assert not satisfies("1.2.4-alpha", "~1.2.3-alpha.3")  # gated: different tuple


def test_x_ranges_and_wildcards():
    assert satisfies("1.9.9", "1.x") and not satisfies("2.0.0", "1.x")
    assert satisfies("1.2.99", "1.2.x") and not satisfies("1.3.0", "1.2.x")
    assert satisfies("0.0.1", "*") and satisfies("99.99.99", "")
    assert not satisfies("1.0.0-alpha", "*")  # bare wildcard never admits prereleases
    assert satisfies("1.3.0", ">1.2.x") and not satisfies("1.2.99", ">1.2.x")
    assert satisfies("0.7.9", "<=0.7.x") and not satisfies("0.8.0", "<=0.7.x")


def test_hyphen_partial_bounds():
    assert satisfies("1.2.0", "1.2 - 2")      # lower widens to >=1.2.0
    assert satisfies("2.9.9", "1.2 - 2")      # upper widens to <3.0.0-0
    assert not satisfies("3.0.0", "1.2 - 2")
    assert satisfies("2.3.0", "1.2.3 - 2.3")  # <2.4.0-0
    assert not satisfies("2.4.0", "1.2.3 - 2.3")
    assert not satisfies("2.5.0-alpha", "1.2 - 2")  # gate: no same-tuple mention


def test_prerelease_gate_is_per_or_alternative():
    assert satisfies("1.2.3-beta", ">=1.2.3-alpha || 3.x")
    assert not satisfies("1.2.3-beta", "1.2.3-alpha || 3.x")  # =-comparator misses
    assert not satisfies("1.2.3-beta", ">=1.2.2 || 3.x")      # no prerelease mention
    assert satisfies("1.2.3-beta", "1.2.3-beta - 2")          # hyphen keeps the mention


def test_invalid_input_never_raises():
    # Note "" and "1.2" are invalid VERSIONS but perfectly valid RANGES.
    bad_versions = [None, 42, 1.5, [], {}, "", "not-a-version", "1.2", "1.2.3.4",
                    "01.2.3", "1.2.3-01", "V1.2.3", "9007199254740992.0.0"]
    for bad in bad_versions:
        assert satisfies(bad, "^1.0.0") is False, f"version {bad!r}"
    bad_ranges = [None, 42, [], "not a range", ">=1.2.3 garbage", "1.2.3 -",
                  ">~1.2.3", ">=x.1", "x.1", "1.x.3", ">=01.2.3", ">"]
    for bad in bad_ranges:
        assert satisfies("1.2.3", bad) is False, f"range {bad!r}"
        assert max_satisfying(["1.2.3"], bad) is None, f"range {bad!r}"
    assert max_satisfying(None, "*") is None
    assert max_satisfying(["junk", None, "1.2.3"], ">=1.0.0") == "1.2.3"


def test_max_satisfying_semantics():
    assert max_satisfying(["1.2.3", "1.2.4", "1.3.0"], "~1.2.3") == "1.2.4"
    assert max_satisfying(["v1.2.3", "1.2.3"], "^1.2.3") == "v1.2.3"  # tie: first wins
    assert max_satisfying(["0.9.0"], "^1.0.0") is None
    assert max_satisfying(["1.2.9", "1.2.10"], "1.2.x") == "1.2.10"  # numeric, not lexicographic
    assert max_satisfying(["1.0.0-alpha", "2.0.0-0"], "*") is None   # all gated out


# --- plain-python runner (no pytest required) -------------------------------

if __name__ == "__main__":
    tests = [
        (name, fn) for name, fn in sorted(globals().items())
        if name.startswith("test_") and callable(fn)
    ]
    failures = 0
    for name, fn in tests:
        try:
            fn()
        except AssertionError as exc:
            failures += 1
            print(f"FAIL {name}\n{exc}")
        else:
            print(f"PASS {name}")

    oracle = _load_oracle()
    n_sat = len(oracle["satisfies"])
    agree_sat = sum(
        1 for v, r, want in oracle["satisfies"] if satisfies(v, r) is want
    )
    n_max = len(oracle["max_satisfying"])
    agree_max = sum(
        1 for vs, r, want in oracle["max_satisfying"] if max_satisfying(vs, r) == want
    )
    print(
        f"\noracle agreement vs node-semver {oracle['semver_version']} "
        f"(node {oracle['node_version']}): satisfies {agree_sat}/{n_sat}, "
        f"max_satisfying {agree_max}/{n_max}"
    )
    print(f"{len(tests) - failures}/{len(tests)} test functions passed")
    sys.exit(1 if failures else 0)
